services:
  - type: web
    name: grace-fidele-atlp-my-brand
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
